# базовые настройки игры
SCREEN_WIDTH = 1000
SCREEN_HEIGHT = 400
GROUND_LEVEL = 350

# физика
GRAVITY = 1
JUMP_STRENGTH = 17
DUCKING_GRAVITY_MULTIPLIER = 3

# скорости
FIREBALL_SPEED = 5
BASE_GAME_SPEED = 5
SPEED_INCREMENT = 1
SPEED_DECREMENT_ON_HIT = 2

# время
SPEED_INCREASE_INTERVAL = 10000
FIREBALL_COOLDOWN = 1000