# базовые настройки игры
SCREEN_WIDTH = 800
SCREEN_HEIGHT = 400
GROUND_LEVEL = 350

# физика
GRAVITY = 1
JUMP_STRENGTH =17
DUCKING_GRAVITY_MULTIPLIER =4

# скорости
FIREBALL_SPEED = 10
BASE_GAME_SPEED = 5
SPEED_INCREMENT = 1

# время
SPEED_INCREASE_INTERVAL = 15000